### ISSUE TITLE
listener: crash/exit after several hours: double free or corruption

### ISSUE THREAD

**Issue by khilman** [pdudaemon/pdudaemon#13]
I've been running a busy pdudaemon (several requests per minute constantly), and lavapdu-listener eventually stops working.  The symptom is errors from pduclient reporting:

  Error sending command, wrong daemon hostname?

But checking in the lavapdu-listener.log, the last line shows:

**\* Error in `/usr/bin/python': double free or corruption (out): 0x00007fbabc0013d0 ***

Using HEAD from this repo
Server platform: x86, Debian jessie

**Comment by khilman** [comment]
Not sure if it's related, but found these in lavapdu-runner.log also.  Without timestamps though, I'm not sure if it's related to the lavapdu-listener crash above or not.

Exception KeyError: KeyError(140542321817344,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by atenart** [comment]
Hi guys,

We do have the exact same issue. Did you find a workaround, or is there any udate about this issue?

Thanks!

**Comment by khilman** [comment]
I never debugged any further.  My "workaround" is that I regularily kill and restart the listener and runner. :(

**Comment by mattface** [comment]
@khilman can you comment on whether this still happens using the latest codebase?

**Comment by khilman** [comment]
No problems with the new codebase.  It's running now for a few weeks with no issues, and no restarts needed.

**Comment by mattface** [comment]
ok, i'm going to close this as no longer applies
