### ISSUE TITLE
Move to asyncio and scrap SQLite backend

### ISSUE THREAD

**Issue by mattface** [pdudaemon/pdudaemon#64]
Running a database for protection between threads is too heavy, so move to asyncio and remove threading.

**Comment by jluebbe** [comment]
This is implemented in https://github.com/pdudaemon/pdudaemon/pull/78.

**Comment by jluebbe** [comment]
This could be closed, as #78 is now merged.

**Comment by mattface** [comment]
@jluebbe many many thanks for the work on this, happy to have it merged!
