### ISSUE TITLE
delay parameter default value

### ISSUE THREAD

**Issue by sephalon** [pdudaemon/pdudaemon#72]
There is some confusion about the intended semantics of the default value for the `delay` parameter. While it makes a lot of sense to put a delay in between the `reboot` command *by default* (i.e. to allow capacitors to discharge), it is not very intuitive why a `on`/`off` command is delayed before execution *by default* as well:

https://github.com/pdudaemon/pdudaemon/blob/80aebfc80402b0aed42d535ea25c410b288a224d/pdudaemon/listener.py#L103

Right now, the Labgrid driver implementation is broken because it only explicitly sets the `delay` parameter for the `shutdown` command:

https://github.com/labgrid-project/labgrid/blob/27126daa04a382d228b0013efcb34e299689be46/labgrid/driver/powerdriver.py#L298-L299

Hence, it would like to ask if the behaviour in PDUDaemon is intended as it is or if the default delay should rather be zero for `on`/`off` commands?

**Comment by mattface** [comment]
It's a good question.

For now I'm happy with a change to make the default 0 for on/off.

I do know that other pdu scripts have support for a delay before and after the request being processed, but as pdudaemon is non-blocking, the after delay would not work unless there was support for making requests blocking.

Maybe we should also accept a delay_before, and a delay_between argument?

Thanks for bringing it up.

**Comment by sephalon** [comment]
Please have a look at my proposal in pull request #74, which applies the delay parameter only to the reboot command anymore. We could add support for a `delay_before` parameter as well if the need arises; this one would apply to all three commands then (`on`, `off` and `reboot`).

**Comment by sephalon** [comment]
AFAIK this issue is done with #74 being merged. Closed.
