### ISSUE TITLE
Question about operate multiple PDU.

### ISSUE THREAD

**Issue by atline** [pdudaemon/pdudaemon#83]
Looks like just one queue in daemon?

Means if just set one PDU daemon for two pdu: pdu1 & pdu2.
Then, the request sent to PDU1 and the request sent to PDU2 will wait in the same queue?
So, suggest to have separate PDU deamon for different PDU? Not just use one PDU deamon for different PDUs?

**Comment by mattface** [comment]
No, there's a separate worker thread for each pdu, so they each have their own queue.

**Comment by atline** [comment]
Clear, thanks.
