### ISSUE TITLE
Where to add the list of PDUs for monitoring? 

### ISSUE THREAD

**Issue by aaamitsingh** [pdudaemon/pdudaemon#94]
Hi, I want to monitor multiple PDUs in my network.  Let's say I have 5 different PDUs from 3 different make with multiple protocol:
1. 2 PDUs supports SNMP
2. 2 PDUs support HTTP
3. 1 PDU support TCP
Now where should I do the configuration or add the lists of PDUs to get the data from the PDUs?

**Comment by mattface** [comment]
Hi,
The pdus are configed in the json config file you pass to the daemon on startup, however it doesnt do any monitoring of PDUs at the moment, PDUDaemon can only give the PDUs commands (on/off).
There's an example config file in /share/

**Comment by jluebbe** [comment]
@aaamitsingh Please reopen if this doesn't answer your question.
