### ISSUE TITLE
Job status API

### ISSUE THREAD

**Issue by sephalon** [pdudaemon/pdudaemon#96]
I did not discover that the Tasmota HTTP response handling fixed in #95 did not work with all our devices until I had a look at the log; this is due to the fact that one cannot query if a job was succesfully executed or not.

The asynchronous nature of the API makes this a bit difficult, however, I think the easiest approach would be to respond with a job ID when a command is queued in; this ID can then later be used to query the job status via a separate API endpoint (queued/successful/failure with error message). What do you think about that?

I am mostly interested in using this together with Labgrid in blocking mode (for which #78 is a prerequisite); in that case, the command response can of course directly contain the job status.

**Comment by sephalon** [comment]
@jluebbe FYI, Labgrid related.

**Comment by obbardc** [comment]
Isn't this no longer relevant since the async job bits have gone from pdudaemon now?

**Comment by jluebbe** [comment]
Yes, you an now wait for the request to finish, which only happens after the PDU set has completed.
